import type { Sandbox } from 'e2b';

const MARKER = '/home/user/.node-app-bootstrapped';
const LOG = '/tmp/node-app-bootstrap.log';

const exists = async (sandbox: Sandbox, path: string): Promise<boolean> => {
  const r = await sandbox.commands.run(`test -e "${path}" && echo yes || echo no`);
  return r.stdout.trim() === 'yes';
};

const have = async (sandbox: Sandbox, binary: string): Promise<boolean> => {
  const r = await sandbox.commands.run(`bash -lc 'export PATH="$HOME/.bun/bin:$PATH"; command -v ${binary}'`);
  return r.stdout.trim().length > 0;
};

const SHELL_PRELUDE = `export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"`;

const PACKAGE_JSON = JSON.stringify(
  {
    name: 'preview',
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'next dev --turbo --port 3000 --hostname 0.0.0.0',
      build: 'next build',
      start: 'next start --port 3000',
    },
    dependencies: {
      next: '^15.0.3',
      react: '^18.3.1',
      'react-dom': '^18.3.1',
    },
    devDependencies: {
      typescript: '^5.6.3',
      '@types/node': '^22.9.0',
      '@types/react': '^18.3.12',
      '@types/react-dom': '^18.3.1',
      tailwindcss: '^3.4.14',
      postcss: '^8.4.49',
      autoprefixer: '^10.4.20',
    },
  },
  null,
  2,
);

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: false,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2,
);

const NEXT_CONFIG = `import type { NextConfig } from 'next';
const nextConfig: NextConfig = { reactStrictMode: true };
export default nextConfig;
`;

const TAILWIND_CONFIG = `import type { Config } from 'tailwindcss';
const config: Config = {
  content: ['./app/**/*.{ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`;

const POSTCSS_CONFIG = `export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
`;

const APP_LAYOUT = `import './globals.css';
import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Preview', description: 'Generated by node-app' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-zinc-900 antialiased">{children}</body>
    </html>
  );
}
`;

const APP_PAGE = `export default function Home() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-24">
      <h1 className="text-4xl font-bold tracking-tight">Welcome to your sandbox</h1>
      <p className="mt-3 text-zinc-600">
        Codex will rewrite this page based on the tree you build in node-app.
      </p>
    </main>
  );
}
`;

const APP_GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

const FILES: Record<string, string> = {
  '/home/user/package.json': PACKAGE_JSON,
  '/home/user/tsconfig.json': TSCONFIG,
  '/home/user/next.config.ts': NEXT_CONFIG,
  '/home/user/tailwind.config.ts': TAILWIND_CONFIG,
  '/home/user/postcss.config.mjs': POSTCSS_CONFIG,
  '/home/user/next-env.d.ts': NEXT_ENV_DTS,
  '/home/user/app/layout.tsx': APP_LAYOUT,
  '/home/user/app/page.tsx': APP_PAGE,
  '/home/user/app/globals.css': APP_GLOBALS_CSS,
};

export const ensureBootstrapped = async (
  sandbox: Sandbox,
  onLog: (line: string) => void,
): Promise<void> => {
  if (await exists(sandbox, MARKER)) {
    await ensureDevServer(sandbox, onLog);
    return;
  }
  onLog('bootstrapping sandbox (one-time, ~2-3 min)…');

  await sandbox.commands.run("pkill -f 'bun create' 2>/dev/null; pkill -f 'shadcn' 2>/dev/null; pkill -f 'create-next-app' 2>/dev/null; true");

  const step = async (label: string, cmd: string, timeoutSec = 300): Promise<void> => {
    onLog(`▸ ${label}`);
    const res = await sandbox.commands.run(
      `bash -lc '${SHELL_PRELUDE}; { ${cmd}; } >> ${LOG} 2>&1'`,
      { timeoutMs: timeoutSec * 1000 },
    );
    if (res.exitCode !== 0) {
      const tail = await sandbox.commands.run(`tail -50 ${LOG} || true`);
      throw new Error(`bootstrap step failed (${label}, exit=${res.exitCode}): ${tail.stdout}`);
    }
  };

  // wipe any residue from prior failed runs but keep .bun / .npm caches
  await step(
    'clean /home/user (preserve caches)',
    "cd /home/user && find . -mindepth 1 -maxdepth 1 ! -name '.bun' ! -name '.npm' ! -name '.config' ! -name '.cache' ! -name '.bashrc' ! -name '.bash_logout' ! -name '.profile' -exec rm -rf {} +",
    60,
  );

  if (!(await have(sandbox, 'bun'))) {
    await step('install bun', 'curl -fsSL https://bun.sh/install | bash', 180);
  } else {
    onLog('▸ bun already installed');
  }

  if (!(await have(sandbox, 'codex'))) {
    await step('install codex CLI', 'npm i -g @openai/codex', 180);
  } else {
    onLog('▸ codex already installed');
  }

  onLog('▸ writing Next.js scaffold');
  await sandbox.files.write('/home/user/app/.gitkeep', '');
  for (const [path, content] of Object.entries(FILES)) {
    await sandbox.files.write(path, content);
  }

  await step('bun install', 'cd /home/user && bun install', 240);
  await step('git init', "cd /home/user && git init -q && git add -A && git -c user.email=bot@local -c user.name=bot commit -q -m init", 30);

  await step('mark bootstrapped', `touch ${MARKER}`, 10);
  await ensureDevServer(sandbox, onLog);
};

const ensureDevServer = async (sandbox: Sandbox, onLog: (line: string) => void): Promise<void> => {
  const portCheck = await sandbox.commands.run(
    `bash -c "exec 3<>/dev/tcp/127.0.0.1/3000 && echo up" 2>/dev/null || true`,
  );
  if (portCheck.stdout.includes('up')) {
    onLog('▸ dev server already up');
    return;
  }

  onLog('▸ starting next dev on :3000');
  await sandbox.commands.run(
    `bash -lc '${SHELL_PRELUDE}; cd /home/user && nohup bun --bun run dev > /tmp/next-dev.log 2>&1 &'`,
    { background: true },
  );

  const deadline = Date.now() + 90_000;
  while (Date.now() < deadline) {
    const r = await sandbox.commands.run(
      `bash -c "exec 3<>/dev/tcp/127.0.0.1/3000 && echo up" 2>/dev/null || true`,
    );
    if (r.stdout.includes('up')) {
      onLog('▸ dev server ready');
      return;
    }
    await Bun.sleep(750);
  }
  const tail = await sandbox.commands.run('tail -30 /tmp/next-dev.log || true');
  throw new Error(`next dev did not start within 90s. log tail:\n${tail.stdout}`);
};
