import type { Sandbox } from 'e2b';

const MARKER = '/home/user/.node-app-bootstrapped';
const LOG = '/tmp/node-app-bootstrap.log';
const SCRIPT = '/tmp/node-app-bootstrap.sh';

const exists = async (sandbox: Sandbox, path: string): Promise<boolean> => {
  const r = await sandbox.commands.run(`test -e "${path}" && echo yes || echo no`);
  return r.stdout.trim() === 'yes';
};

const PACKAGE_JSON = JSON.stringify(
  {
    name: 'preview',
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'next dev --turbo --port 3000 --hostname 0.0.0.0',
      build: 'next build',
      start: 'next start --port 3000',
    },
    dependencies: {
      next: '^15.0.3',
      react: '^18.3.1',
      'react-dom': '^18.3.1',
    },
    devDependencies: {
      typescript: '^5.6.3',
      '@types/node': '^22.9.0',
      '@types/react': '^18.3.12',
      '@types/react-dom': '^18.3.1',
      tailwindcss: '^3.4.14',
      postcss: '^8.4.49',
      autoprefixer: '^10.4.20',
    },
  },
  null,
  2,
);

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: false,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2,
);

const NEXT_CONFIG = `import type { NextConfig } from 'next';
const nextConfig: NextConfig = { reactStrictMode: true };
export default nextConfig;
`;

const TAILWIND_CONFIG = `import type { Config } from 'tailwindcss';
const config: Config = {
  content: ['./app/**/*.{ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`;

const POSTCSS_CONFIG = `export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
`;

const APP_LAYOUT = `import './globals.css';
import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Preview', description: 'Generated by node-app' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-zinc-900 antialiased">{children}</body>
    </html>
  );
}
`;

const APP_PAGE = `export default function Home() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-24">
      <h1 className="text-4xl font-bold tracking-tight">Welcome to your sandbox</h1>
      <p className="mt-3 text-zinc-600">
        Codex will rewrite this page based on the tree you build in node-app.
      </p>
    </main>
  );
}
`;

const APP_GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

const FILES: Record<string, string> = {
  '/home/user/package.json': PACKAGE_JSON,
  '/home/user/tsconfig.json': TSCONFIG,
  '/home/user/next.config.ts': NEXT_CONFIG,
  '/home/user/tailwind.config.ts': TAILWIND_CONFIG,
  '/home/user/postcss.config.mjs': POSTCSS_CONFIG,
  '/home/user/next-env.d.ts': NEXT_ENV_DTS,
  '/home/user/app/layout.tsx': APP_LAYOUT,
  '/home/user/app/page.tsx': APP_PAGE,
  '/home/user/app/globals.css': APP_GLOBALS_CSS,
};

const BOOTSTRAP_SCRIPT = `#!/usr/bin/env bash
set -euo pipefail
export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
exec > >(tee -a ${LOG}) 2>&1
echo "===== bootstrap $(date -Iseconds) ====="

echo ">> cleaning /home/user (preserve caches)"
cd /home/user
shopt -s extglob dotglob
rm -rf !(.bun|.npm|.config|.cache|.bashrc|.bash_logout|.profile|.)
shopt -u extglob dotglob

if ! command -v bun >/dev/null; then
  echo ">> install bun"
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
fi
echo "bun: $(bun --version)"

if ! command -v codex >/dev/null; then
  echo ">> install codex CLI"
  npm i -g @openai/codex
fi
echo "codex: $(codex --version 2>/dev/null || echo missing)"
`;

const POST_FILES_SCRIPT = `#!/usr/bin/env bash
set -euo pipefail
export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
exec >> ${LOG} 2>&1
echo ">> bun install"
cd /home/user
bun install
echo ">> git init"
git init -q || true
git add -A
git -c user.email=bot@local -c user.name=bot commit -q -m init || true
echo ">> done"
touch ${MARKER}
`;

const runScript = async (
  sandbox: Sandbox,
  script: string,
  onLog: (line: string) => void,
  timeoutMs: number,
): Promise<void> => {
  await sandbox.files.write(SCRIPT, script);
  await sandbox.commands.run(`chmod +x ${SCRIPT}`);

  // start in background, tail the log for progress
  await sandbox.commands.run(`nohup bash ${SCRIPT} > /dev/null 2>&1 &`, { background: true });

  // tail log lines until the marker shows up OR the script exits
  const deadline = Date.now() + timeoutMs;
  let lastSize = 0;
  let seenDone = false;
  while (Date.now() < deadline) {
    const r = await sandbox.commands.run(`wc -c < ${LOG} 2>/dev/null || echo 0`);
    const size = Number(r.stdout.trim()) || 0;
    if (size > lastSize) {
      const chunk = await sandbox.commands.run(`tail -c +${lastSize + 1} ${LOG} | head -c 8192`);
      for (const line of chunk.stdout.split('\n')) {
        if (line.trim()) onLog(line);
        if (line.includes('>> done')) seenDone = true;
      }
      lastSize = size;
    }
    if (seenDone) return;
    // check if script process is still alive
    const alive = await sandbox.commands.run(`pgrep -f 'bash ${SCRIPT}' >/dev/null && echo y || echo n`);
    if (alive.stdout.trim() === 'n' && !seenDone) {
      // process exited; one last log flush
      const final = await sandbox.commands.run(`tail -c +${lastSize + 1} ${LOG}`);
      for (const line of final.stdout.split('\n')) if (line.trim()) onLog(line);
      throw new Error('bootstrap script exited without writing >> done marker');
    }
    await Bun.sleep(1000);
  }
  throw new Error(`bootstrap timed out after ${timeoutMs / 1000}s`);
};

export const ensureBootstrapped = async (
  sandbox: Sandbox,
  onLog: (line: string) => void,
): Promise<void> => {
  if (await exists(sandbox, MARKER)) {
    await ensureDevServer(sandbox, onLog);
    return;
  }
  onLog('bootstrapping sandbox (one-time, ~2-3 min)…');

  // kill anything that might be hanging from a prior run
  await sandbox.commands.run(
    "pkill -f 'bun create' 2>/dev/null; pkill -f 'shadcn' 2>/dev/null; pkill -f 'create-next-app' 2>/dev/null; pkill -f 'node-app-bootstrap' 2>/dev/null; true",
  );
  await sandbox.commands.run(`rm -f ${LOG}`);

  // phase 1: clean + install bun + install codex
  await runScript(sandbox, BOOTSTRAP_SCRIPT, onLog, 5 * 60_000);

  // phase 2: write scaffold files
  onLog('▸ writing Next.js scaffold');
  for (const [path, content] of Object.entries(FILES)) {
    await sandbox.files.write(path, content);
  }

  // phase 3: bun install + git init + mark
  await runScript(sandbox, POST_FILES_SCRIPT, onLog, 5 * 60_000);

  await ensureDevServer(sandbox, onLog);
};

const ensureDevServer = async (sandbox: Sandbox, onLog: (line: string) => void): Promise<void> => {
  const portCheck = await sandbox.commands.run(
    `bash -c "exec 3<>/dev/tcp/127.0.0.1/3000 && echo up" 2>/dev/null || true`,
  );
  if (portCheck.stdout.includes('up')) {
    onLog('▸ dev server already up');
    return;
  }

  onLog('▸ starting next dev on :3000');
  await sandbox.commands.run(
    `bash -lc 'export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"; cd /home/user && nohup bun --bun run dev > /tmp/next-dev.log 2>&1 &'`,
    { background: true },
  );

  const deadline = Date.now() + 120_000;
  while (Date.now() < deadline) {
    const r = await sandbox.commands.run(
      `bash -c "exec 3<>/dev/tcp/127.0.0.1/3000 && echo up" 2>/dev/null || true`,
    );
    if (r.stdout.includes('up')) {
      onLog('▸ dev server ready');
      return;
    }
    await Bun.sleep(1000);
  }
  const tail = await sandbox.commands.run('tail -40 /tmp/next-dev.log || true');
  throw new Error(`next dev did not start within 120s. log tail:\n${tail.stdout}`);
};
