import type { Sandbox } from 'e2b';

const MARKER = '/home/user/.node-app-bootstrapped';
const LOG = '/tmp/node-app-bootstrap.log';
const CODEX_SDK_PACKAGE = '@openai/codex-sdk@0.130.0';
const CODEX_SDK_RUNNER_DIR = '/tmp/node-app-codex-sdk-runner';

const exists = async (sandbox: Sandbox, path: string): Promise<boolean> => {
  const r = await sandbox.commands.run(`test -e "${path}" && echo yes || echo no`);
  return r.stdout.trim() === 'yes';
};

const PACKAGE_JSON = JSON.stringify(
  {
    name: 'preview',
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'next dev --turbo --port 3000 --hostname 0.0.0.0',
      build: 'next build',
      start: 'next start --port 3000',
    },
    dependencies: {
      next: '^15.0.3',
      react: '^18.3.1',
      'react-dom': '^18.3.1',
    },
    devDependencies: {
      typescript: '^5.6.3',
      '@types/node': '^22.9.0',
      '@types/react': '^18.3.12',
      '@types/react-dom': '^18.3.1',
      tailwindcss: '^3.4.14',
      postcss: '^8.4.49',
      autoprefixer: '^10.4.20',
    },
  },
  null,
  2,
);

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: false,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2,
);

const NEXT_CONFIG = `import type { NextConfig } from 'next';
const nextConfig: NextConfig = { reactStrictMode: true };
export default nextConfig;
`;

const TAILWIND_CONFIG = `import type { Config } from 'tailwindcss';
const config: Config = {
  content: ['./app/**/*.{ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`;

const POSTCSS_CONFIG = `export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
`;

const APP_LAYOUT = `import './globals.css';
import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Preview', description: 'Generated by node-app' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-zinc-900 antialiased">{children}</body>
    </html>
  );
}
`;

const APP_PAGE = `export default function Home() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-24">
      <h1 className="text-4xl font-bold tracking-tight">Welcome to your sandbox</h1>
      <p className="mt-3 text-zinc-600">
        Codex will rewrite this page based on the tree you build in node-app.
      </p>
    </main>
  );
}
`;

const APP_GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

const FILES: Record<string, string> = {
  '/home/user/package.json': PACKAGE_JSON,
  '/home/user/tsconfig.json': TSCONFIG,
  '/home/user/next.config.ts': NEXT_CONFIG,
  '/home/user/tailwind.config.ts': TAILWIND_CONFIG,
  '/home/user/postcss.config.mjs': POSTCSS_CONFIG,
  '/home/user/next-env.d.ts': NEXT_ENV_DTS,
  '/home/user/app/layout.tsx': APP_LAYOUT,
  '/home/user/app/page.tsx': APP_PAGE,
  '/home/user/app/globals.css': APP_GLOBALS_CSS,
};

const BOOTSTRAP_SCRIPT = `#!/usr/bin/env bash
set -eu
set -x
export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
echo "===== bootstrap $(date -Iseconds) ====="

echo ">> cleaning /home/user (preserve caches)"
cd /home/user
for entry in $(ls -A1 /home/user); do
  case "$entry" in
    .bun|.npm|.config|.cache|.bashrc|.bash_logout|.profile) ;;
    *) rm -rf "/home/user/$entry" ;;
  esac
done

if ! command -v bun >/dev/null; then
  echo ">> install bun"
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
fi
echo "bun: $(bun --version)"

echo ">> install/upgrade codex CLI to latest (template ships 0.101 which lacks gpt-5 model support)"
npm i -g @openai/codex@latest
echo "codex: $(codex --version 2>/dev/null || echo missing)"
echo ">> install Codex SDK runner dependencies"
rm -rf ${CODEX_SDK_RUNNER_DIR}
mkdir -p ${CODEX_SDK_RUNNER_DIR}
npm install --prefix ${CODEX_SDK_RUNNER_DIR} ${CODEX_SDK_PACKAGE} --no-audit --no-fund --loglevel=error
echo ">> phase1 done"
`;

const POST_FILES_SCRIPT = `#!/usr/bin/env bash
set -eu
set -x
export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
cd /home/user

# add 1GB swap so npm install can spill — default sandbox is 1GB RAM
if [ ! -e /swapfile ]; then
  echo ">> adding swap"
  (sudo fallocate -l 1G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile) 2>/dev/null || echo "swap setup skipped"
fi

echo ">> npm install (lighter on memory than bun install)"
npm install --no-audit --no-fund --omit=optional --loglevel=error

echo ">> git init"
git init -q || true
git add -A
git -c user.email=bot@local -c user.name=bot commit -q -m init || true
touch ${MARKER}
echo ">> done"
`;

const runScript = async (
  sandbox: Sandbox,
  scriptPath: string,
  script: string,
  onLog: (line: string) => void,
  timeoutMs: number,
  doneMarker: string,
): Promise<void> => {
  console.info(`[bootstrap] writing ${scriptPath} (${script.length} bytes)`);
  await sandbox.commands.run(`bash -c "rm -f ${scriptPath}"`);
  await sandbox.files.write(scriptPath, script);
  await sandbox.commands.run(`chmod +x ${scriptPath}`);
  const check = await sandbox.commands.run(`ls -la ${scriptPath}`);
  console.info(`[bootstrap] script written: ${check.stdout.trim()}`);

  const initialSize = await sandbox.commands.run(`wc -c < ${LOG} 2>/dev/null || echo 0`);
  let lastSize = Number(initialSize.stdout.trim()) || 0;
  console.info(`[bootstrap] launching: nohup bash ${scriptPath} >> ${LOG} 2>&1 &`);
  await sandbox.commands.run(`nohup bash ${scriptPath} >> ${LOG} 2>&1 &`, { background: true });

  const deadline = Date.now() + timeoutMs;
  let seenDone = false;
  while (Date.now() < deadline) {
    const r = await sandbox.commands.run(`wc -c < ${LOG} 2>/dev/null || echo 0`);
    const size = Number(r.stdout.trim()) || 0;
    if (size > lastSize) {
      const chunk = await sandbox.commands.run(`tail -c +${lastSize + 1} ${LOG} | head -c 8192`);
      for (const line of chunk.stdout.split('\n')) {
        if (line.trim()) onLog(line);
        if (line.includes(doneMarker)) seenDone = true;
      }
      lastSize += chunk.stdout.length;
      if (lastSize > size) lastSize = size;
    }
    if (seenDone) {
      console.info(`[bootstrap] saw '${doneMarker}'`);
      return;
    }
    const alive = await sandbox.commands.run(`pgrep -f '[b]ash ${scriptPath}' >/dev/null && echo y || echo n`);
    if (alive.stdout.trim() === 'n' && !seenDone) {
      const final = await sandbox.commands.run(`tail -c +${lastSize + 1} ${LOG} 2>/dev/null || true`);
      for (const line of final.stdout.split('\n')) if (line.trim()) onLog(line);
      const fullLog = await sandbox.commands.run(`cat ${LOG} 2>/dev/null || echo EMPTY`);
      console.error(`[bootstrap] script exited without marker. Full log:\n${fullLog.stdout}`);
      throw new Error(`bootstrap script exited without writing '${doneMarker}'`);
    }
    await Bun.sleep(1000);
  }
  throw new Error(`bootstrap timed out after ${timeoutMs / 1000}s`);
};

export const ensureBootstrapped = async (
  sandbox: Sandbox,
  onLog: (line: string) => void,
): Promise<void> => {
  console.info('[bootstrap] checking marker');
  if (await exists(sandbox, MARKER)) {
    console.info('[bootstrap] marker present, skipping to dev server');
    await ensureDevServer(sandbox, onLog);
    return;
  }
  onLog('bootstrapping sandbox (one-time, ~2-3 min)…');
  console.info('[bootstrap] starting fresh');

  await sandbox.commands.run(`bash -c "rm -f ${LOG} && true"`);

  console.info('[bootstrap] phase 1: install bun + codex');
  await runScript(sandbox, '/tmp/node-app-bootstrap-1.sh', BOOTSTRAP_SCRIPT, onLog, 5 * 60_000, '>> phase1 done');

  console.info('[bootstrap] phase 2: write scaffold files');
  onLog('▸ writing Next.js scaffold');
  for (const [path, content] of Object.entries(FILES)) {
    await sandbox.files.write(path, content);
  }

  console.info('[bootstrap] phase 3: bun install + finalize');
  await runScript(sandbox, '/tmp/node-app-bootstrap-2.sh', POST_FILES_SCRIPT, onLog, 5 * 60_000, '>> done');

  await ensureDevServer(sandbox, onLog);
};

export const ensureDevServer = async (sandbox: Sandbox, onLog: (line: string) => void): Promise<void> => {
  const portCheck = await sandbox.commands.run(
    `bash -c "exec 3<>/dev/tcp/127.0.0.1/3000 && echo up" 2>/dev/null || true`,
  );
  if (portCheck.stdout.includes('up')) {
    const status = await sandbox.commands.run(`curl -sS -o /tmp/node-app-preview-check.html -w "%{http_code}" --max-time 5 http://127.0.0.1:3000 || true`);
    if (status.stdout.trim().startsWith('5')) {
      const log = await sandbox.commands.run('tail -120 /tmp/next-dev.log || true');
      const hasCorruptNextCache =
        log.stdout.includes('/home/user/.next/static/development/_buildManifest.js.tmp') ||
        log.stdout.includes('/home/user/.next/server/app/_not-found/page/app-build-manifest.json');
      if (hasCorruptNextCache) {
        onLog('▸ Next.js dev cache is corrupted; rebuilding preview server');
        await sandbox.commands.run(
          `bash -lc "ss -ltnp 'sport = :3000' | sed -n 's/.*pid=\\([0-9][0-9]*\\).*/\\1/p' | sort -u | xargs -r kill; rm -rf /home/user/.next /tmp/next-dev.log"`,
        );
      } else {
        onLog('▸ dev server already up');
        return;
      }
    } else {
      onLog('▸ dev server already up');
      return;
    }
  }

  const portCheckAfterCleanup = await sandbox.commands.run(
    `bash -c "exec 3<>/dev/tcp/127.0.0.1/3000 && echo up" 2>/dev/null || true`,
  );
  if (portCheckAfterCleanup.stdout.includes('up')) {
    onLog('▸ dev server already up');
    return;
  }

  onLog('▸ starting next dev on :3000');
  await sandbox.commands.run(
    `bash -lc 'export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"; cd /home/user && nohup bun --bun run dev > /tmp/next-dev.log 2>&1 &'`,
    { background: true },
  );

  const deadline = Date.now() + 120_000;
  while (Date.now() < deadline) {
    const r = await sandbox.commands.run(
      `bash -c "exec 3<>/dev/tcp/127.0.0.1/3000 && echo up" 2>/dev/null || true`,
    );
    if (r.stdout.includes('up')) {
      onLog('▸ dev server ready');
      return;
    }
    await Bun.sleep(1000);
  }
  const tail = await sandbox.commands.run('tail -40 /tmp/next-dev.log || true');
  throw new Error(`next dev did not start within 120s. log tail:\n${tail.stdout}`);
};
